- Dockerfile
Pushing to aptible fails, apparently because config/database.yml.example isn't recognized.
Let's try commenting out that line since that's not a file we have in our app.
> Tweak Dockerfile for Aptible push.

- app/assets/stylesheets/student.scss
- app/views/students/_school_year_box.html.erb
makes referrals more readable.  This:
instead of this:
> Groups office referrals in student profile view

- Gemfile
- Gemfile.lock
I found this helpful as a newcomer to the project.  A [simple command](http://voormedia.github.io/rails-erd/install.html#generate) generates a diagram of model relationships.
> Add ERD gem for easy diagram creation

- app/models/school_year.rb
- app/views/students/_school_year_box.html.erb
* STAR results sorted by descending date
* Em-dashes that capture missing values like so:
> Fix STAR results in profile view

- app/views/students/index.html.erb
* [tablesort](https://github.com/tristen/tablesort) wasn't using numerical sort because the em dashes for blank values were confusing it
* Now it knows what to do
> Fix table sort bug 

- app/assets/stylesheets/student.scss
Makes highcharts play nice on different browsers.
Firefox:
Chrome:
> Fix Firefox issue with Highcharts

- app/assets/stylesheets/overall.scss
- app/models/student_risk_level.rb
- app/views/students/_student_row.html.erb
- app/views/students/show.html.erb
Some students are missing key pieces of information needed to calculate risk level.
Quick styling for those cases.
__Profile:__
__Roster:__
> Styles for Risk Level: N/A

- app/assets/javascripts/profile.js
- app/assets/javascripts/roster.js
- app/controllers/students_controller.rb
- app/views/students/_mcas_row_fragment.html.erb
- app/views/students/_star_math_row_fragment.html.erb
- app/views/students/_star_reading_row_fragment.html.erb
- app/views/students/_student_row.html.erb
- app/views/students/show.html.erb
When you click on a behavior data point on the roster...
... you go to the behavior chart on the profile:
etc.
> Roster click-through to corresponding profile chart

- app/assets/javascripts/roster.js
- app/views/students/_student_row.html.erb
- app/views/students/index.html.erb
+ Make SPED info part of default roster view — critical info for educators
+ Take out SPED placement status column since this is info educators already know
+ Based on principal & educator feedback from Somerville via @marimuraki
> Make SPED part of default roster view

- app/views/students/_school_year_box.html.erb
- db/seeds/demo/demo_data/fake_dibels_result_generator.rb
- DIBELS level are no longer case-sensitive so e.g., both "Core" and "CORE" will be captured in the profile
- included "Benchmark" as "Core"
> capture non-case-sensitive DIBELS levels

- app/assets/javascripts/application.js
- app/assets/javascripts/roster.js
- app/controllers/homerooms_controller.rb
- app/views/homerooms/_student_row.html.erb
- app/views/homerooms/show.html.erb
- vendor/assets/javascripts/js.cookie.js
* When an educator switches back & forth between the roster and student profiles, column selects for the roster are maintained:
* See #214.
> Handle roster columns state with cookies

- README.md
Hi,
just a small correction in the README.
> correct typo in README: rails c => rails s

- app/csv_exporters/student_profile_csv_demographic_section.rb
- app/csv_exporters/student_profile_csv_exporter.rb
- spec/features/export_profile_feature_spec.rb
- previously CSV export only included {attendance, behavior, assessments}
- now includes demographics as listed in student profile
- updated specs
#72
> add demographics information to profile CSV export #72

- app/assets/stylesheets/table.scss
Hi,
this css-change seems to fix the following issue:
The header broke into lines, when the header was wider than the content of the table cells (e.g. in the case "STAR: Math" - see #240 )
Please retest it.
> roster: nowrap for column group headers #240

- app/controllers/application_controller.rb
- app/controllers/homerooms_controller.rb
- app/models/educator.rb
- db/seeds/demo/demo_educator.seeds.rb
- db/seeds/demo/demo_students.seeds.rb
- spec/controllers/homerooms_controller_spec.rb
- spec/factories/educators.rb
- spec/factories/homerooms.rb
+ Admin-level educators can see roster view for all homerooms
+ Non-admin educators can only see the roster for their own homerooms, plus other homerooms at their grade level, as per feedback we've gotten from Healey teachers and @jsgeiser
+ In demo mode, add a new login: `fake-fifth-grade@example.com` / `demo-password`, which can only see fifth-grade demo classrooms
> Educator homeroom permissions

- app/models/student.rb
- app/views/students/_school_year_box.html.erb
Hi,
while writing tests for the new risk level calculation, I noticed a small inconsistency - which made writing tests for access results a little bit more difficult.
In the model Student:
the method access returns a single access assessment,
but it can also return a MissingStudentAssessmentCollection, if some data is missing.
The other methods which return only a single assessment, always return MissingStudentAssessment as "nil object".
Does this have a specific reason?
If not, please review this pull request :-)
Cheers,
r11runner
> access returns MissingStudentAssessment as nil object instead of MissingStudentAssessmentCollection

- app/assets/stylesheets/table.scss
Two fewer lines of CSS — way better front-end lqqk on Firefox:
#290
> Fix firefox front-end

- README.md
Hi,
I've just tried to set up the somerville-teacher-tool project on my old-new laptop with Ubuntu 15.04 and I've run (again) into this issue.
```
rake db:create
```
throws an error, unless I remove the line
```
host: localhost
```
from the config of the development db. (The test db gets created as expected.) Ca. 2 months ago, I had the same issue on an Ubuntu 14.04 system.
According to [this Stackoverflow-discussion](http://stackoverflow.com/questions/23375740/pgconnectionbad-fe-sendauth-no-password-supplied), on Debian-like systems localhost refers to a TCP connection => password is required. So
- either I have to set "host: localhost", username and password
- or also omit the line "host: localhost"
Feel free this reject this pull request or replace it with a better / more detailed …
> readme: added note about configuring the dev db on a Debian-like system

- app/assets/javascripts/application.js
- app/assets/javascripts/session_timeout_warning.js
- app/assets/stylesheets/nav.scss
- app/controllers/educators_controller.rb
- app/views/layouts/application.html.erb
- config/initializers/devise.rb
- config/routes.rb
- spec/controllers/educators_controller_spec.rb
+ Client-side option to renew sessions, which expire automatically after 15 minutes with Devise `timeoutable` on the server side
+ Important to have because educators were finding their flow interrupted by unexpected timeout when clicking a link on the page
+ #326
> Give educator a "renew session" link

- app/views/interventions/create.js.erb
- app/views/progress_notes/create.js.erb
+ Useful in JS views where we render data with multiline text descriptions
+ Without JS escaping, AJAX responses like create.js.erb were failing
+ This prevented confirmation messages from appearing & data from rendering, confusing users
+ Fixes #334
> Escape carriage returns for JS strings

- app/assets/stylesheets/nav.scss
- app/controllers/schools_controller.rb
- app/models/educator.rb
- app/models/homeroom_queries.rb
- app/views/layouts/application.html.erb
- app/views/schools/_homeroom_table.html.erb
- app/views/schools/homerooms.erb
- app/views/students/show.html.erb
- config/routes.rb
- spec/controllers/schools_controller_spec.rb
What's new?
A minimal "at-risk classrooms" page, for identifying the classrooms that have students most in need of support, in terms of MCAS scores, absences and tardies.  This is just a starting point, and essentially mirrors the "students at risk" page to start.  Links are added to the header for minimal navigation.
There are also two small unrelated changes.  First, changing the "back" link text on the student back to say which classroom it links to, and fixing a bug in the students association on the Educator model.
Classrooms view:
Navigation links:
Update link text, back to roster for particular classroom:
> Add minimal classrooms page and navigation links to the header

- app/assets/stylesheets/schools.css
- app/controllers/schools_controller.rb
- app/views/schools/homerooms.erb
- app/views/schools/show.html.erb
This updates the controller results to cap the number of classrooms, and also fixes the min-height of the tables.
See production URL at https://somerville-teacher-tool.herokuapp.com/schools/2/homerooms to see tables not aligning and not capping results.
After:
> Cap number of classrooms returned on classroom risk page

- app/assets/javascripts/student/interventions_controller.js
- app/assets/javascripts/student/interventions_controller_templates.hbs
- app/assets/stylesheets/buttons.scss
- app/controllers/interventions_controller.rb
- app/models/intervention.rb
- db/migrate/20151231193719_add_custom_intervention_name_to_intervention.rb
- db/schema.rb
- spec/factories/interventions.rb
- spec/factories/students.rb
- spec/javascripts/student/interventions_controller_spec.js
- spec/models/intervention_spec.rb
* Feature idea from @jsgeiser via email: 
_"For the intervention list, where it says "other", can we have a place to label that "other" intervention? I have been using that one a bit."_
> Add custom intervention types

- app/models/student.rb
- spec/models/student_spec.rb
@alexsoble This was what we were seeing with the STAR math scores the other day.  I don't think it affects anything else, looks like the roster and profile pages access this data a different way.
The next `rake update:recent_assessments` run tomorrow should fix this, and I can verify that before Friday.
> Fix bug with updating most_recent_star_math_percentile attribute

- app/importers/settings/somerville_settings.rb
- app/importers/star_math_importer.rb
- app/importers/star_reading_importer.rb
- spec/importers/star_math_importer_spec.rb
- spec/importers/star_reading_importer_spec.rb
+ STAR's historical file can conflict in some ways with X2
+ As the SIS, X2 should be the sole source of truth about students
+ For example, the STAR historical file doesn't know whether students are active or inactive in Somerville Public Schools
+ We don't want X2 to not import a student because they are active and then have STAR create a shell student object with no attributes besides STAR results
> Revoke STAR importers' ability to create new students

- app/assets/javascripts/components/school_overview_page.js
- spec/javascripts/components/school_overview_page_spec.js
@jsgeiser said it best:
> "One question – when I click on multiple filter under one category, it won’t recognize that. (e.g. clicking on Free lunch and reduced lunch). Is there a way to click on more than one filter in a category?"
Allow Jill and other administrators to set filters that show students using OR combinations. 
For example: `Free lunch OR Reduced lunch AND Advanced math`
Also speed up performance: https://github.com/codeforamerica/somerville-teacher-tool/issues/383#issuecomment-173970574
> Use OR logic for school overview filters within the same category

- app/assets/javascripts/school/star_reading_page.js
- app/controllers/schools_controller.rb
- app/models/intervention_type.rb
- lib/development_fixtures.rb
- spec/controllers/bulk_intervention_assignments_controller_spec.rb
- spec/controllers/interventions_controller_spec.rb
- spec/factories/interventions.rb
I ran into problems trying to use fixture data, where the InterventionTypes seeded for development don't match production.  So this updates the seed method to use the same values in production.  There were a few specs that relied on specific `intervention_type_ids`, so it required updating those as well.
There's also some methods in `schools_controller` that weren't necessary anymore, so that was cleaned out as well as an update to take advantage of the new `student.most_recent_school_year.discipline_incidents.count`.
Finally, a small visual change to remove padding around the filters that was in the STAR data page and not the school overview page.
> Update seed InterventionTypes to match production, split out DevelopmentFixtures

- config/unicorn.rb
We've been prototyping some new features that are using inefficient Rails queries (e.g., on STAR reading visualizations), and we'd like to defer optimizing them for a few more days.  This PR increases the Unicorn timeout to address occasional 500s, which based on these log messages are from Heroku timing out waiting for the Rails app:
```
2016-01-28T20:19:27.179750+00:00 heroku[router]: at=error code=H13 desc="Connection closed without response" method=GET path="/schools/hea/star_reading" host=somerville-teacher-tool.herokuapp.com request_id=5f1e0a10-f332-4ed4-b531-dbdad7b8f381 fwd="207.172.212.174" dyno=web.1 connect=0ms service=15813ms status=503 bytes=0
```
> Increase Unicorn timeout for prototyping new features shipped dark

- app/controllers/schools_controller.rb
- spec/controllers/schools_controller_spec.rb
This endpoint was timing out (over 30 seconds).  This makes some quick optimizations to includes some associations eagerly to get it reliably functional, although I think it'll still be worth adding a precompute task for this next week.
Benchmark.measure on the console showing times of [10, 17, 7, 9] seconds, so a noticeable enough improvement to ship and the revisit again.
> Optimize query in star_reading endpoint, fixing timeouts

- app/importers/educator_row.rb
- app/importers/educators_importer.rb
- spec/importers/educators_importer_spec.rb
+ Only import Administrators plus teachers with homerooms for now
+ Data on the remainder of `staff` is ambiguous; see #388 
+ Import the rest and authorize once our understanding of X2 `staff` is clearer 
+ We may decide to use principal admin pages for educator authorization if X2 `staff` data quality stays poor and we can't improve it quickly enough
> Get simple educator permissions from X2

- spec/controllers/schools_controller_spec.rb
- spec/controllers/students_controller_spec.rb
- spec/factories/educators.rb
- spec/factories/homerooms.rb
- spec/factories/students.rb
- spec/features/export_profile_feature_spec.rb
- spec/features/profile_feature_spec.rb
+ There are plenty of methods to test on Student that don't rely on a StudentRiskLevel
+ When StudentRiskLevel is part of the Student factory by default, it makes changing StudentRiskLevel more difficult
> Remove student risk level as a default on student factory

- app/assets/javascripts/school/helpers/routes.js
+ `baseURL` shouldn't be set to production URL; this breaks the app in development and demo environments
+ Plus the URL can change over time
> Make overview page links work in different environments

- app/assets/javascripts/student/interventions_controller_templates.hbs
- app/assets/javascripts/student/student_notes_controller_templates.hbs
- app/assets/stylesheets/student.scss
- app/assets/stylesheets/student_note.scss
Previously, if users were using whitespace in text fields (eg., line breaks, spaces), they wouldn't be rendered back to them.
Notes page, before:
Notes page, after:
Intervention text, before:
Intervention text, after:
Progress note, before:
Progress note, after:
> Render whitespace for user-entered text

- app/assets/javascripts/school_overview/school_overview_page.js
This was just `student.csv` in the initial version, update it to have the date and data about filters applied as well.
> Make download as CSV filename more explicit on dashboard page

- app/controllers/application_controller.rb
- app/controllers/educators_controller.rb
- app/controllers/homerooms_controller.rb
- spec/controllers/homerooms_controller_spec.rb
I encountered a redirect to the "Looks like there's no homeroom assigned to you." page earlier on the demo site, and @marimuraki reported the same thing too.
This happens because the educator account doesn't have a `default_homeroom` set.  This is valid for administrators though (which is what the `demo@` account is supposed to show).  This updates code in `homerooms_controller` that redirects to the user's default homeroom in some failure scenarios (like if the user doesn't have a homeroom set, or the homeroom id is invalid).
This change pushes the branching for the homepage URL based on role down to a `homepage_path_for_role` method in `application_controller`, and uses that instead.
You can reproduce visiting `/homerooms/foo` as an admin user, which perhaps was coming up on the demo …
> Change redirect from invalid homeroom_id to respect user role

- app/assets/javascripts/application.js
- app/assets/javascripts/env.js.erb
- app/assets/javascripts/helpers/mixpanel_utils.js
Track whether user sessions are happening on production site or demo site (both useful in different ways).
> Expose Rails env and DEMO_SITE flag to JS UI, include it in usage metrics

- app/models/educator.rb
+ I removed Devise `:validatable` because we no longer store user passwords because LDAP
+ But that removed email uniqueness validation too!
+ We don't want multiple Educator records with the same email address
> Restore email uniqueness validation

- app/controllers/students_controller.rb
- app/importers/educator_row.rb
- app/importers/educators_importer.rb
- app/models/educator.rb
- app/models/educator_summary.rb
- app/views/layouts/application.html.erb
- app/views/pages/not_authorized.html.erb
- config/routes.rb
- db/migrate/20160204001545_add_permissions_fields_for_educators.rb
- db/migrate/20160204003848_add_default_value_to_educator_grade_level_access.rb
- db/migrate/20160204033744_add_restricted_access_fields_to_educators.rb
- db/schema.rb
- lib/exceptions.rb
- spec/controllers/homerooms_controller_spec.rb
- spec/controllers/students_controller_spec.rb
- spec/factories/educators.rb
- spec/features/export_profile_feature_spec.rb
- spec/features/profile_feature_spec.rb
- spec/importers/educators_importer_spec.rb
- spec/models/educator_spec.rb
+ Allow scoping educator access to student profiles and homeroom rosters by grade level
+ Allow scoping educator access to student profiles by student's SPED/Limited English status (i.e. SPED staff can only see profiles for students in SPED; ELL specialists can only see profiles for students with some kind of limited english proficiency status)
+ New permissions system has roughly four tiers:
1. Schoolwide access
2. Grade-level access to multiple grades (can be restricted by student's SPED / ELL status)
3. Homeroom-level access (which gives access to one grade level)
4. No access
+ Not all queries are ready for multi-school tenancy yet
+ Code in the concept of district-wide access: right now principals and district admins have the same permissions because there's only one school's worth …
> More granular permissions for educators

- app/models/educator.rb
- spec/factories/educators.rb
- spec/models/educator_spec.rb
+ When an unnamed developer (me) rolls educator records by hand and doesn't add the LASID (district-assigned local ID), that screws with the data flow later on
+ When the stream of educators coming in from X2 includes an educator that has been hand-rolled, it will need to match up to the educator by LASID
+ Otherwise it will throw `ActiveRecord::RecordInvalid` on the non-unique email value
> Validate educator LASIDs

- app/controllers/application_controller.rb
- app/controllers/schools_controller.rb
- app/models/educator.rb
- app/presenters/school_student_presenter.rb
- spec/controllers/homerooms_controller_spec.rb
- spec/controllers/schools_controller_spec.rb
- spec/models/educator_spec.rb
+ Educators with access beyond a single homeroom + grade level root to school overview page
+ Their version of the school overview page includes students only within permitted grade levels
+ School overview page now takes a specific collection of students instead of all of 'em
> Smarter page defaults and permissions for educators

- app/importers/educator_row.rb
- spec/importers/educators_importer_spec.rb
+ X2 knows about admin status, and all admins have schoolwide access
+ But not all those with schoolwide access are admins!
+ Specialists who work across the entire school need schoolwide access to
+ And their roles are being set with a seed task, not via the X2 data link
> Don't set schoolwide access via X2
