- app/assets/stylesheets/style.css
- app/views/pages/index.html.erb
> css style updates

- app/assets/stylesheets/style.css
- app/views/pages/index.html.erb
> Homeroom dropdown

- app/assets/stylesheets/style.css
> style updates

- app/assets/javascripts/script.js
- app/assets/stylesheets/style.css
- app/views/pages/index.html.erb
> Nav update

- Gemfile
- Gemfile.lock
- app/controllers/students_controller.rb
- app/views/students/index.html.erb
- spec/factories/users.rb
- spec/features/sign_in_feature_spec.rb
- spec/rails_helper.rb
- spec/student_spec.rb
* Implement Capybara. 
* Simple feature tests for login flow.
> Better tests

- app/models/school.rb
- app/models/student.rb
- db/migrate/20150319003233_create_schools.rb
- db/migrate/20150319003722_change_attribute_type.rb
- db/migrate/20150319010755_add_school_i_dto_student.rb
- db/migrate/20150320004303_add_limited_english_proficientto_student.rb
- db/migrate/20150320004424_add_former_limited_english_proficientto_student.rb
- db/migrate/20150320005825_change_lep_and_flep_to_boolean.rb
- db/migrate/20150320011837_remove_limited_english_from_students.rb
- db/schema.rb
- db/seeds/schools.seeds.rb
- lib/modules/data_helpers.rb
- lib/tasks/import_district_data.rake
- lib/tasks/import_mcas.rake
- spec/factories/schools.rb
Pull in @marimuraki's MCAS import logic!
> Import mcas

- app/assets/stylesheets/homeroom.scss
- app/assets/stylesheets/nav.scss
- app/assets/stylesheets/overall.scss
- app/assets/stylesheets/table.scss
- app/assets/stylesheets/type.scss
- app/assets/stylesheets/variables.scss
- app/views/students/index.html.erb
+ Increased contrast for Risk levels
+ Increased whitespace for Risk levels
+ Moved nav to right to decrease height of header
+ Cleaned stylesheets in sass
> Risk sections

- app/analyzers/risk_analyzer.rb
- app/controllers/pages_controller.rb
- app/controllers/students_controller.rb
- app/models/student.rb
- spec/analyzers/risk_analyzer_spec.rb
- spec/factories/student.rb
- spec/factories/student_results.rb
Benefits of having a separate class for sorting: 
+ Cleaner
+ Easier to read
+ Easier to test
> Refactor how students are sorted by risk category

- app/controllers/pages_controller.rb
- app/controllers/students_controller.rb
- app/importers/mcas_importer.rb
- app/importers/star_importer.rb
- app/importers/star_math_importer.rb
- app/importers/star_reading_importer.rb
- app/models/assessment.rb
- app/models/mcas_result.rb
- app/models/star_result.rb
- app/models/student.rb
- app/presenters/mcas_result_presenter.rb
- app/presenters/star_result_presenter.rb
- app/views/students/_student_row.html.erb
- app/views/students/index.html.erb
- db/migrate/20150425135201_blow_away_assessments.rb
- db/migrate/20150425135257_add_date_taken_to_results.rb
- db/schema.rb
- db/seeds/fake/fake_students.seeds.rb
- db/seeds/import/mcas.seeds.rb
- db/seeds/import/star.seeds.rb
- spec/fixtures/fake_star_math.csv
- spec/fixtures/fake_star_reading.csv
- spec/importers/mcas_importer_spec.rb
- spec/importers/star_importer_spec.rb
+ STAR results and MCAS results have a date_taken attribute
+ Blow away Assessment model, it wasn't doing much for us
+ Refactor our STAR Importer to handle reading and math results more gracefully. Polymorphism! :+1:
> Capture STAR test dates

- app/importers/attendance_importer.rb
- app/importers/mcas_importer.rb
- app/importers/star_importer.rb
- app/importers/x2_importer.rb
- app/models/student.rb
- db/migrate/20150502105856_rename_state_identifier_to_state_id.rb
- db/schema.rb
- lib/modules/fake_student.rb
- spec/factories/student.rb
- spec/factories/students.rb
- spec/fixtures/fake_attendance.rb
- spec/importers/attendance_importer_spec.rb
- spec/importers/mcas_importer_spec.rb
+ Fix bug in risk analyzer that let students fall under multiple categories
+ Since we're ditching this risk analyzer soon, no use in testing it
+ But while the analyzer lives, it should work!
+ Add validation for state id to prevent future potential duplicate students
+ Rename state_identifier to state_id since it is clearer, shorter, more Rails-idiomatic
> No duplicate students

- app/importers/attendance_importer.rb
- app/importers/mcas_importer.rb
- app/importers/x2_importer.rb
- db/seeds/import/attendance.seeds.rb
- db/seeds/import/mcas.seeds.rb
- db/seeds/import/x2.seeds.rb
- spec/importers/mcas_importer_spec.rb
- spec/importers/x2_importer_spec.rb
* We are planning on testing with Healey classrooms across different grade levels in June, so let's import use data for all Healey School, not just Grade 5.
> Remove filter by grade for data import

- app/assets/stylesheets/about.scss
- app/assets/stylesheets/controls.scss
- app/assets/stylesheets/nav.scss
- app/assets/stylesheets/overall.scss
- app/assets/stylesheets/table.scss
- app/assets/stylesheets/tooltip.scss
- app/assets/stylesheets/variables.scss
- app/views/students/index.html.erb
- vendor/assets/stylesheets/tablesort.css
Cleaning up responsiveness and styles of the table including the table headers alignment.
> Table clean up

- app/assets/javascripts/application.js
- app/assets/javascripts/table.js
- app/assets/stylesheets/table.scss
- app/assets/stylesheets/variables.scss
Added clickable rows and hovers. Cleaned table styles and bubble color.
> Table navigation

- app/assets/images/placeholder.svg
- app/assets/javascripts/profile.js
- app/assets/stylesheets/overall.scss
- app/assets/stylesheets/student.scss
- app/views/students/show.html.erb
- db/seeds/demo/demo_students.seeds.rb
addresses issue #97 by displaying message in place of chart. 
possible solution to displaying graphic: http://www.highcharts.com/demo/combo-timeline 
possible solution to centering: maybe there's something built into HighCharts?
> Handle student zero-case charting

- Gemfile
- Gemfile.lock
- app/assets/javascripts/profile.js
- db/seeds/demo/demo_data/fake_attendance_event.rb
- db/seeds/demo/demo_data/fake_discipline_incident.rb
- db/seeds/demo/demo_data/fake_student.rb
- db/seeds/demo/demo_students.seeds.rb
Student first and last names via faker,
Attendance and discipline events with some simple probabilities (could
be better)
Addresses issue #94
> Adds variety to db seed data

- app/assets/javascripts/profile.js
- config/database.yml
Earlier commit [student-profile](https://github.com/codeforamerica/somerville-teacher-tool/commit/8825afa9a9df0d99608334d1d915484d8c8e10ea) broke how zero-case was tested for, this commit fixes that.
> Zero case fix

- app/importers/star_importer.rb
- app/importers/star_math_importer.rb
- app/importers/star_reading_importer.rb
- lib/tasks/import_from_star.rake
- spec/fixtures/bad_star_math_data.csv
- spec/fixtures/bad_star_reading_data.csv
- spec/fixtures/fake_star_math.csv
- spec/fixtures/fake_star_reading.csv
- spec/importers/star_importer_spec.rb
- spec/importers/star_math_importer_spec.rb
- spec/importers/star_reading_importer_spec.rb
Fetch STAR assessment data from remote site (as opposed to importing data from file on local machine)
> STAR pipeline

- app/assets/javascripts/profile.js
- app/controllers/students_controller.rb
- app/importers/mcas_importer.rb
- app/models/attendance_event.rb
- app/models/discipline_incident.rb
- app/models/mcas_result.rb
- app/models/school_year.rb
- app/models/star_result.rb
- app/models/student.rb
- app/views/students/_school_year_box.html.erb
- app/views/students/show.html.erb
- config/initializers/devise.rb
- db/migrate/20150619235056_add_school_year_id_to_mcas_result_and_star_result.rb
- db/schema.rb
- lib/modules/assign_to_school_year.rb
- spec/factories/mcas_results.rb
- spec/factories/star_results.rb
- spec/fixtures/fake_mcas.csv
- spec/importers/mcas_importer_spec.rb
- spec/models/mcas_result_spec.rb
- spec/models/star_result_spec.rb
- x2_export/assessment_export.sql
+ Import MCAS data from X2 on a nightly basis
+ Add assessments (MCAS, STAR) to student profile chart
+ Add assessments (MCAS, STAR) to school year infoboxes on student profile
> Add MCAS & STAR to student profile

- app/presenters/student_presenter.rb
- app/views/students/_school_year_box.html.erb
- app/views/students/_student_row.html.erb
- spec/factories/educators.rb
- spec/factories/students.rb
- spec/features/profile_feature_spec.rb
- spec/features/roster_feature_spec.rb
- spec/features/sign_in_feature_spec.rb
More automated tests! Check to make sure that:
1. Roster view renders the correct number of student rows, and
2. Profile view includes assessments / attendance / behavior infoboxes that match student records
> Add feature tests

- x2_export/behavior_export.sql
* Make sure that we've scrubbed out quotes-within-quotes from behavior free text blobs
> Get easier-to-user behavior data from X2

- app/importers/star_importer.rb
- app/importers/students_importer.rb
- app/importers/x2_importer.rb
- db/migrate/20150626142214_add_local_id_to_student.rb
- db/schema.rb
- lib/tasks/import_from_star.rake
- lib/tasks/import_from_x2.rake
- lib/tasks/import_healey_from_star.rake
- lib/tasks/import_healey_from_x2.rake
- lib/tasks/summer_school_mode.rake
- spec/importers/mcas_importer_spec.rb
- spec/importers/star_importer_spec.rb
- spec/importers/x2_importer_spec.rb
- x2_export/students_export.sql
* Build a hacky rack task that simulates what summer school looks like (organized by grade level instead of by homeroom)
* Import LASIDs (Locally Assigned Student IDs) so that we can have our machine read the summer school registration sheet
* Trick out importer module a bit with a nice terminal progressbar
> Somerschool Mode!

- app/importers/behavior_importer.rb
- app/importers/x2_importer.rb
- db/migrate/20150629142658_change_discipline_incident_description_to_text.rb
- db/schema.rb
- spec/fixtures/fake_behavior_export.txt
- spec/importers/behavior_importer_spec.rb
* Encoding: Windows 1252 to UTF-8 (thanks @migurski)
* Data:
* More date/time checks for sanity & data quality
* Handle incident descriptions as text, not string
* Convert "\N" field values to Ruby `nil`
> Handle encoding & data issues for behavior import

- app/importers/importer.rb
- app/importers/star_importer.rb
- app/importers/star_math_importer.rb
- app/importers/star_reading_importer.rb
- app/importers/x2_importer.rb
- lib/tasks/summer_school_mode.rake
* Summer school-only import modes for X2 and STAR
> Refactor importers

- db/seeds/demo/demo_data/fake_mcas_result.rb
- db/seeds/demo/demo_data/fake_star_result.rb
- db/seeds/demo/demo_students.seeds.rb
Create more realistic fake assessment results for MCAS and STAR
- MCAS 1x/year
- STAR multiple times a year (make look like more frequent local classroom assessments)
- assessment to assessment differences within % range
- bound by min / max values
> Create more realistic fake assessment result

- app/presenters/student_presenter.rb
- app/views/students/_student_row.html.erb
- app/views/students/index.html.erb
* Show home language in roster view
* Hide SPED, Limited English, and Free/Reduced Lunch until we figure out the best way to store those data fields (strings? boolean? EdFi? #156?)
> Show home language in roster

- app/views/layouts/application.html.erb
* Specify document language as English 
* Close HTML tags that need closing
> HTML improvements 

- app/models/student.rb
Sorting MCAS & START results in CSV export in new to old order (similar to the sort for attendance and behavior).
> Sort MCAS & STAR results in CSV export

- app/assets/stylesheets/student.scss
- app/importers/students_importer.rb
- app/presenters/student_presenter.rb
- app/views/students/_school_year_box.html.erb
- app/views/students/show.html.erb
- db/migrate/20150721214158_add_demographics_columns_to_student.rb
- db/migrate/20150721214344_update_limited_english_attributes.rb
- db/migrate/20150721221555_change_free_reduced_lunch_to_string.rb
- db/schema.rb
- db/seeds/demo/demo_data/fake_student.rb
- db/seeds/demo/demo_students.seeds.rb
- spec/factories/students.rb
- spec/fixtures/fake_students_export.txt
- spec/importers/students_importer_spec.rb
- spec/importers/x2_importer_spec.rb
- spec/presenters/student_presenter_spec.rb
> Add SPED, English Learner information to student profile

- app/assets/javascripts/profile.js.erb
- app/assets/stylesheets/student.scss
- app/assets/stylesheets/variables.scss
- app/views/students/show.html.erb
> Add risk level button

- app/assets/javascripts/application.js
- app/assets/javascripts/risk_sort.js
- app/assets/stylesheets/overall.scss
- app/assets/stylesheets/student.scss
- app/assets/stylesheets/table.scss
- app/assets/stylesheets/variables.scss
- app/models/mcas_result.rb
- app/models/missing_assessment.rb
- app/models/star_result.rb
- app/models/student.rb
- app/views/devise/confirmations/new.html.erb
- app/views/students/_student_row.html.erb
- app/views/students/_warning_indicator.html.erb
- app/views/students/index.html.erb
- app/views/students/show.html.erb
- spec/factories/students.rb
- spec/models/student_spec.rb
> Define risk levels, add to roster & profile

- app/assets/stylesheets/about.scss.erb
- app/assets/stylesheets/type.scss
- app/assets/stylesheets/variables.scss
- app/views/layouts/application.html.erb
- app/views/pages/about.html.erb
> Fix a11y issues

- app/assets/javascripts/mcas_sort.js
- app/assets/javascripts/risk_sort.js
- app/assets/javascripts/roster.js
- app/assets/stylesheets/controls.scss
- app/presenters/student_presenter.rb
- app/views/students/_student_row.html.erb
- app/views/students/index.html.erb
Roster view now includes:
+ SPED & disability information
+ Free/reduced lunch
+ English proficiency information
> Add columns to roster

- app/assets/javascripts/chart_settings.js
- app/assets/stylesheets/controls.scss
- app/assets/stylesheets/nav.scss
- app/assets/stylesheets/student.scss
- app/assets/stylesheets/tooltip.scss
- app/assets/stylesheets/variables.scss
- app/views/students/index.html.erb
Updating styles to match V2 designs
> Update styles to V2 #180

- app/assets/javascripts/profile.js
- app/assets/javascripts/roster.js
- app/assets/stylesheets/student.scss
- app/assets/stylesheets/tooltip.scss
- app/views/students/index.html.erb
- app/views/students/show.html.erb
* Pretty new tooltip styles:
* Refactored tooltip CSS :+1:
> Update tooltip styles

- app/assets/stylesheets/overall.scss
- app/assets/stylesheets/student.scss
- app/assets/stylesheets/student_type.scss
- app/assets/stylesheets/table.scss
- app/assets/stylesheets/tooltip.scss
- app/assets/stylesheets/type.scss
- app/assets/stylesheets/variables.scss
- app/views/students/_mcas_row_fragment.html.erb
- app/views/students/_school_year_box.html.erb
- app/views/students/_star_math_row_fragment.html.erb
- app/views/students/_star_reading_row_fragment.html.erb
- app/views/students/_student_row.html.erb
- app/views/students/index.html.erb
- db/seeds/demo/demo_data/fake_star_math_result_generator.rb
- vendor/assets/stylesheets/tablesort.css
> Style me pretty

- README.md
- lib/tasks/import.rake
+ The name of this branch is a lie. We are not parsing options on the command line at all! 
+ Rather, we are punting data import options to ENV variables. 
+ Allow import configuration per district / charter network as ENV variable.
+ Update README with info about how to import real school district data.
+ Real school district data :grey_exclamation:
> Import options

- app/assets/stylesheets/overall.scss
- app/assets/stylesheets/student.scss
- app/assets/stylesheets/table.scss
- app/assets/stylesheets/variables.scss
- app/risk_levels/student_risk_level.rb
Add color to risk level. Updated risk level design & wording in
profile. With @marimuraki :D
> Add Risk level 0

- app/assets/javascripts/charts/chart_settings.js
- app/assets/javascripts/charts/mcas_growth_chart.js
- app/assets/javascripts/charts/star_chart.js
Added benchmark plotlines per feedback from Vince & principals #172
- warning threshold
- expected threshold
> add benchmark & warning plotlines to MCAS & STAR graphs #172

- app/assets/javascripts/charts/chart_settings.js
- app/assets/javascripts/charts/mcas_scaled_chart.js
> correct MCAS scale score graph axes with appropriate scale #230

- app/assets/javascripts/charts/chart_settings.js
- app/assets/javascripts/charts/mcas_scaled_chart.js
**BEFORE**
**NEW**
Refer to https://github.com/codeforamerica/somerville-teacher-tool/issues/172 for more details
> add MCAS scale score to performance level bands #172

- app/assets/stylesheets/student.scss
- app/charts/student_profile_chart.rb
- app/csv_exporters/student_profile_csv_assessment_section.rb
- app/csv_exporters/student_profile_csv_exporter.rb
- app/models/assessment.rb
- app/models/missing_assessment_collection.rb
- app/models/school_year.rb
- app/views/students/_school_year_box.html.erb
- app/views/students/show.html.erb
- lib/modules/find_data_for_student_profile.rb
- spec/factories/assessments.rb
- spec/factories/students.rb
- spec/features/profile_feature_spec.rb
- spec/importers/bulk_attendance_importer_spec.rb
Our fake student Pocahontas Poppins has new assessment results on her student profile page:
> Add DIBELS, ACCESS results to profile

- app/models/assessment.rb
- app/models/missing_assessment_collection.rb
- app/models/school_year.rb
- app/views/students/_school_year_box.html.erb
- lib/modules/find_data_for_student_profile.rb
- spec/factories/students.rb
- spec/features/profile_feature_spec.rb
+ Make student profile look a little more like #180.
+ Pocahontas Poppins's fake STAR results section:
+ TODO: #177
> Group STAR results by date

- app/assets/javascripts/charts/chart_settings.js
- simple wording change from "Expected" to "Average baseline" (ask teachers & etc for specific wording that might be better)
> re-word plotline text

- app/assets/images/calendar-icon.svg
- app/assets/javascripts/charts/intervention_plot_band.js
- app/assets/javascripts/charts/mcas_growth_chart.js
- app/assets/javascripts/charts/mcas_scaled_chart.js
- app/assets/javascripts/charts/star_chart.js
- app/assets/javascripts/profile.js
- app/assets/stylesheets/application.css
- app/assets/stylesheets/student.scss
- app/charts/student_profile_chart.rb
- app/controllers/interventions_controller.rb
- app/controllers/students_controller.rb
- app/models/intervention.rb
- app/models/intervention_type.rb
- app/models/student.rb
- app/views/students/show.html.erb
- config/routes.rb
- db/migrate/20150814134606_create_interventions.rb
- db/migrate/20150814134617_create_intervention_types.rb
- db/migrate/20150814134735_add_educator_id_to_intervention.rb
- db/migrate/20150814194236_change_start_and_end_date_to_dates.rb
- db/schema.rb
- db/seeds/demo/demo_data/fake_intervention.rb
- db/seeds/demo/demo_students.seeds.rb
- spec/controllers/interventions_controller_spec.rb
- spec/factories/intervention_types.rb
- spec/factories/interventions.rb
- spec/javascripts/charts/intervention_plot_band_spec.js
> Interventions

- app/models/missing_student_assessment.rb
- app/presenters/student_presenter.rb
- app/views/students/_school_year_box.html.erb
- db/seeds/demo/demo_data/fake_student.rb
- spec/presenters/student_presenter_spec.rb
- clean up how the roster & profile to handle null cases
- remove irrelevant information cluttering the profile
> Tweak roster profile

- app/assets/stylesheets/overall.scss
- app/controllers/homerooms_controller.rb
- app/helpers/pages_helper.rb
- app/helpers/roster_helper.rb
- app/helpers/students_helper.rb
- app/helpers/users_helper.rb
- app/views/homerooms/_access_row_fragment.html.erb
- app/views/homerooms/_dibels_row_fragment.html.erb
- app/views/homerooms/_mcas_row_fragment.html.erb
- app/views/homerooms/_star_math_row_fragment.html.erb
- app/views/homerooms/_star_reading_row_fragment.html.erb
- app/views/homerooms/_student_row.html.erb
- app/views/homerooms/show.html.erb
* Make the roster page load feel way snappier by:
1. loading rows pre-sorted by risk level and 
2. hiding roster columns with CSS instead of js on page load
> Make the ride smoother

- app/importers/students_importer.rb
- app/models/homeroom.rb
- app/views/homerooms/_dibels_row_fragment.html.erb
- app/views/homerooms/_mcas_row_fragment.html.erb
- app/views/homerooms/_star_math_row_fragment.html.erb
- app/views/homerooms/_star_reading_row_fragment.html.erb
- app/views/homerooms/show.html.erb
- db/migrate/20150820013958_add_grade_to_homeroom.rb
- db/schema.rb
- db/seeds/demo/demo_students.seeds.rb
- spec/models/homeroom_spec.rb
* On the roster, only show the assessments that make sense for the homeroom
*  i.e. show DIBELS results for younger homerooms, MCAS/STAR for older ones
> Only show assessments relevant to homeroom

- app/assets/javascripts/charts/mcas_growth_chart.js
- app/assets/javascripts/charts/mcas_scaled_chart.js
- app/assets/javascripts/charts/star_chart.js
- app/assets/javascripts/profile.js
- spec/javascripts/charts/intervention_plot_band_spec.js
> Add Interventions to legend

- app/controllers/homerooms_controller.rb
- app/models/student_rows_query.rb
- app/views/homerooms/show.html.erb
- spec/factories/student_assessments.rb
- spec/factories/students.rb
- spec/models/student_rows_query_spec.rb
+ Pull homeroom queries into their own object
+ Cut number of instance variables in controller action
+ Use `detect` instead of `select` for more concise code
> Refactor homeroom queries

- app/assets/stylesheets/variables.scss
- updating colors based on pairing w/ @AmirHadjihabib #240
> change risk level colors

- app/controllers/homerooms_controller.rb
- app/views/homerooms/show.html.erb
- update default roster view now that MCAS & STAR are broken up by subject https://github.com/codeforamerica/somerville-teacher-tool/pull/253
- default view includes: `name`, `risk`, `sped`, `mcas_math`, `mcas_ela`
> update default roster view

- db/migrate/20150825185246_add_unique_indexes_to_homerooms.rb
- db/schema.rb
+ Database-level uniqueness on homeroom names
+ Concept via @derekprior: https://robots.thoughtbot.com/the-perils-of-uniqueness-validations
+ #258
> Add uniqueness constraint to homeroom names at db level

- app/presenters/generic_assessment_value_presenter.rb
- app/presenters/mcas_value_presenter.rb
- app/presenters/star_value_presenter.rb
- app/presenters/student_assessment_presenter.rb
- app/presenters/student_presenter.rb
- app/presenters/student_row_presenter.rb
- db/seeds/demo/demo_data/fake_star_reading_result_generator.rb
- spec/presenters/generic_assessment_value_presenter_spec.rb
- spec/presenters/mcas_value_presenter_spec.rb
- spec/presenters/student_assessment_presenter_spec.rb
- spec/presenters/student_presenter_spec.rb
> Refactor presenters

- Gemfile
- Gemfile.lock
- app/controllers/homerooms_controller.rb
- app/models/student_rows_query.rb
- app/views/homerooms/_access_row_fragment.html.erb
- app/views/homerooms/_dibels_row_fragment.html.erb
- app/views/homerooms/_mcas_row_fragment.html.erb
- app/views/homerooms/_star_math_row_fragment.html.erb
- app/views/homerooms/_star_reading_row_fragment.html.erb
- app/views/homerooms/_student_row.html.erb
- app/views/homerooms/show.html.erb
- spec/factories/educators.rb
- spec/factories/homerooms.rb
- spec/factories/student_assessments.rb
- spec/factories/students.rb
- spec/features/roster_feature_spec.rb
- spec/models/student_rows_query_spec.rb
* Use one big SQL query to fetch student + student assessments for roster
* Roster speed: 958.1ms
* Number of queries: 7 
* Separate queries needed for educator authorization, building homerooms dropdown
* #210
> One big SQL query

- app/controllers/homerooms_controller.rb
- app/importers/healey_after_school_tutoring_importer.rb
- app/importers/settings/somerville_settings.rb
- app/models/intervention.rb
- app/models/intervention_type.rb
- app/models/school_year.rb
- app/models/student.rb
- app/models/student_rows_query.rb
- app/presenters/student_row_presenter.rb
- app/views/homerooms/_student_row.html.erb
- app/views/homerooms/show.html.erb
- app/views/students/show.html.erb
- db/migrate/20150826181638_add_number_of_hours_to_intervention.rb
- db/migrate/20150830191132_add_school_year_id_to_intervention.rb
- db/schema.rb
- db/seeds/demo/demo_data/fake_intervention.rb
- lib/modules/assign_to_school_year.rb
- lib/tasks/interventions.thor
- spec/factories/educators.rb
- spec/factories/homerooms.rb
- spec/factories/interventions.rb
- spec/factories/students.rb
- spec/features/roster_feature_spec.rb
> Add ATP hours to roster

- app/views/students/show.html.erb
> corrected typo: disabiity => disability

- app/assets/javascripts/application.js
- app/assets/javascripts/datepicker.js
- app/assets/javascripts/profile.js
- app/assets/javascripts/roster.js
- app/assets/javascripts/roster_bulk_assignment.js
- app/assets/stylesheets/overall.scss
- app/assets/stylesheets/override.scss
- app/assets/stylesheets/roster.scss
- app/assets/stylesheets/student.scss
- app/assets/stylesheets/style.scss
- app/assets/stylesheets/table.scss
- app/assets/stylesheets/type.scss
- app/controllers/bulk_intervention_assignments_controller.rb
- app/controllers/homerooms_controller.rb
- app/controllers/interventions_controller.rb
- app/models/bulk_intervention_assignment.rb
- app/models/intervention_type.rb
- app/views/bulk_intervention_assignments/create.js.erb
- app/views/bulk_intervention_assignments/new.html.erb
- app/views/homerooms/_student_row.html.erb
- app/views/homerooms/show.html.erb
- app/views/layouts/application.html.erb
- app/views/students/show.html.erb
- config/routes.rb
- db/migrate/20150914172000_add_goal_to_intervention.rb
- db/schema.rb
- spec/controllers/bulk_intervention_assignments_controller_spec.rb
> Bulk assign interventions from roster

- app/assets/javascripts/application.js
- app/assets/javascripts/roster.js
- app/assets/stylesheets/roster.scss
- app/assets/stylesheets/table.scss
- vendor/assets/javascripts/classList.js
> Fix things in IE 9

- app/assets/images/menu.svg
- app/assets/javascripts/roster.js
- app/assets/stylesheets/roster.scss
- app/assets/stylesheets/table.scss
- app/views/homerooms/show.html.erb
> Roster interventions styles

- app/controllers/students_controller.rb
Based on teacher & principal feedback from Somerville.
> Order interventions list by start date

- app/assets/javascripts/application.js
- app/assets/javascripts/roster.js
- app/assets/javascripts/student-searchbar.js
- app/assets/stylesheets/controls.scss
- app/controllers/students_controller.rb
- app/views/homerooms/show.html.erb
- app/views/layouts/application.html.erb
- app/views/students/show.html.erb
- config/routes.rb
- spec/controllers/students_controller_spec.rb
- spec/factories/students.rb
> Student searchbar

- app/models/intervention_type.rb
@alexsoble: Needed to correct the interventions list --- had a duplicate.
> correct interventions list

- README.md
These came up when I was installing locally.
> Add notes about Postgres and Puma installation

- .gitignore
- app/controllers/application_controller.rb
- app/controllers/educators_controller.rb
- app/controllers/homerooms_controller.rb
- app/controllers/interventions_controller.rb
- app/controllers/pages_controller.rb
- app/controllers/progress_notes_controller.rb
- app/controllers/students_controller.rb
- config/database.example.yml
- spec/controllers/bulk_intervention_assignments_controller_spec.rb
+ Make controllers require authorization by default, instead of on a per-controller basis
+ Clarify that `database.yml` is an example file by renaming to `database.example.yml`
> Security updates

- app/assets/javascripts/student/interventions_controller.js
- app/assets/javascripts/student/interventions_controller_templates.hbs
- app/assets/javascripts/student/student_notes_controller.js
- app/assets/javascripts/student/student_notes_controller_templates.hbs
- app/assets/javascripts/student/student_page.js
- app/assets/stylesheets/buttons.scss
- app/assets/stylesheets/panels.scss
- app/assets/stylesheets/student.scss
- app/assets/stylesheets/student_note.scss
- app/assets/stylesheets/style.scss
- app/controllers/interventions_controller.rb
- app/controllers/progress_notes_controller.rb
- app/controllers/student_notes_controller.rb
- app/controllers/students_controller.rb
- app/helpers/serialize_data_helper.rb
- app/models/educator.rb
- app/models/student.rb
- app/models/student_note.rb
- app/views/students/show.html.erb
- config/routes.rb
- db/migrate/20151218231639_create_student_notes.rb
- db/schema.rb
- spec/controllers/student_notes_controller_spec.rb
- spec/javascripts/student/student_notes_controller_spec.js
> Add student notes feature

- app/models/homeroom.rb
- app/models/homeroom_queries.rb
- app/views/schools/homerooms.erb
- spec/controllers/schools_controller_spec.rb
- spec/factories/attendance_events.rb
- spec/factories/student_assessments.rb
- spec/factories/student_school_years.rb
- spec/factories/students.rb
- spec/models/homeroom_spec.rb
+ Bug fixes for classrooms-at-risk view
+ Worked smoothly with demo data, ran into more `nil` values in production
+ More specs for classrooms-at-risk view
> Classrooms at risk bugfix

- app/models/homeroom_queries.rb
- app/presenters/homeroom_presenter.rb
- app/views/schools/_homeroom_table.html.erb
FYI @kevinrobinson, from our gchat conversation the other day. :0)
> Add grade level to classrooms at risk tables

- app/assets/javascripts/student/interventions_controller.js
- app/assets/javascripts/student/interventions_controller_templates.hbs
- app/assets/javascripts/student/student_page.js
- app/assets/stylesheets/student.scss
- app/controllers/interventions_controller.rb
- app/views/layouts/application.html.erb
- spec/controllers/homerooms_controller_spec.rb
- spec/controllers/interventions_controller_spec.rb
- spec/controllers/schools_controller_spec.rb
- spec/factories/educators.rb
- spec/javascripts/spec_helper.js
- spec/javascripts/student/interventions_controller_spec.js
* Functionality restricted to admins, as per guidance & feedback from @jsgeiser
* #333
> Allow admins (principals) to delete interventions

- app/models/student_risk_level.rb
- spec/models/student_risk_level_spec.rb
* Break up the codebase's most complex method into smaller ones.
> Refactor StudentRiskLevel method

- app/assets/javascripts/student/interventions_controller.js
- spec/javascripts/student/interventions_controller_spec.js
> Bugfix: Fix custom intervention flow on IE

- app/importers/clients/sftp_client.rb
- app/importers/connector.rb
- app/importers/educators_importer.rb
- app/importers/importer.rb
- app/importers/settings/somerville_settings.rb
- app/importers/students_importer.rb
- app/models/educator.rb
- db/migrate/20160111163236_add_attributes_to_educators.rb
- db/migrate/20160112013803_remove_uniqueness_contraint_on_educator_email.rb
- db/schema.rb
- lib/tasks/import.thor
- spec/factories/educators.rb
- spec/factories/homerooms.rb
- spec/importers/educators_importer_spec.rb
* When LDAP handles authentication, X2 will need to handle authorization — i.e. by regualting which classroom teachers should be associated with which homerooms
* Side benefit: factored out totally unnecessary complexity from import settings class
* Prerequisite for #328
* Prerequisite for #325
> Import basic educator information from X2

- app/importers/clients/sftp_client.rb
- app/importers/connector.rb
- app/importers/importer.rb
- app/importers/settings/somerville_settings.rb
- app/importers/star_math_importer.rb
- app/importers/star_reading_importer.rb
- lib/tasks/import.thor
- spec/importers/settings/somerville_settings_spec.rb
+ Consume new historical STAR data files added to SFTP site
+ Fix bug with credentials for STAR import process
+ Test import in more detail
+ Make import logs more verbose in production
> Consume historical STAR data

- Gemfile
- Gemfile.lock
- app/csv_exporters/student_profile_csv_exporter.rb
+ Cherry-picked cleanup commits from larger branch that's not ready to be merged in yet
> Clean up Gemfile;  fix require 'csv' placement

- README.md
- app/controllers/bulk_intervention_assignments_controller.rb
- app/controllers/educators_controller.rb
- app/controllers/homerooms_controller.rb
- app/controllers/interventions_controller.rb
- app/controllers/pages_controller.rb
- app/controllers/progress_notes_controller.rb
- app/controllers/schools_controller.rb
- app/controllers/student_notes_controller.rb
- app/controllers/students_controller.rb
- app/importers/attendance_importer.rb
- app/importers/behavior_importer.rb
- app/importers/educators_importer.rb
- app/importers/student_assessment_importer.rb
- app/importers/students_importer.rb
+ Update README with Quotaguard Static and LDAP configuration information
+ Add code comments to controllers
+ Add code comments to importers outlining remote CSV file expectations
> More documentation

- app/importers/importer.rb
- lib/tasks/import.thor
- spec/fixtures/fake_students_export.txt
- spec/importers/importer_spec.rb
- spec/importers/students_importer_spec.rb
+ Old options let developer select either all schools or 1 school for data import
+ Now add option to import elementary schools as a group
> Add import mode for elementary schools

- app/helpers/school_local_id_to_app_id.rb
- app/importers/educators_importer.rb
- spec/importers/educators_importer_spec.rb
- x2_export/educators_export.sql
That way we can authorize staff to the correct school data.
> Link staff to schools via X2 data

- app/assets/javascripts/school/star_reading_page.js
This updates the filtering on graphs that focus on "recent" assessments.  Previously this was just fixed to the current period, and this generalizes it to call out students that have had assessments in the last 90 days.
> Updated definition of recent assessment to be more general in STAR reading graphs

- x2_export/educators_export.sql
+ Import educator login name so we can match against emails for correct authorization
+ Import `status` column even though the data isn't very accurate right now
+ If we can help improve processes, maybe it will become more accurate and useful in the future!
> Import staff data from x2

- app/models/student_risk_level.rb
- db/migrate/20160130143407_store_student_risk_level_factors.rb
- db/schema.rb
- spec/controllers/schools_controller_spec.rb
+ Precompute and store the value of each risk level factor
+ That way we can eventually stop storing the generated explanation in the db and create it on the fly with a presenter, without needing to query Student at all
+ Replace arrays of pre-defined explanation phrases with a lookup table by risk factor and level
> Refactor student risk level

- app/assets/javascripts/school/components/slice_panels.js
- app/assets/javascripts/school/overview_page.js
> Use homeroom name instead of ID on schools overview page

- app/assets/javascripts/student/student_page.js
This wasn't added in the previous PR (we're working on revising the profile page in #373), but is good to have as baseline beforehand.
> Add metrics for student profile views

- app/assets/javascripts/student_searchbar.js
- app/assets/stylesheets/override.scss
- app/controllers/students_controller.rb
- app/models/student.rb
- spec/controllers/students_controller_spec.rb
- spec/factories/students.rb
+ Handle no search results case
+ Reduce font size to match the rest of the app
+ Include student school and grade level
> Improve student searchbar

- app/models/educator.rb
+ We'll want to do data quality checks on what which educators are in the DB and what their roles are
+ #388
> Write simple summary report for educator counts

- app/models/educator_summary.rb
+ Add option to scope by school
+ Add report for educators missing LASIDs
> Tweak educator summary report
